import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bot,Copy,Menu,MessageSquarePlus,Send,Sparkles,Trash2,User,X} from 'lucide-react';
import './styles.css';
const STARTER={role:'model',text:"Hey! I'm your Gemini-powered assistant. Ask me anything."};
const SUGGESTIONS=['Explain a difficult concept simply','Help me debug some code','Give me a study plan','Brainstorm a project idea'];
function App(){
 const [messages,setMessages]=useState([STARTER]),[input,setInput]=useState(''),[loading,setLoading]=useState(false),[menuOpen,setMenuOpen]=useState(false); const bottomRef=useRef(null),ta=useRef(null);
 useEffect(()=>bottomRef.current?.scrollIntoView({behavior:'smooth'}),[messages,loading]);
 const newChat=()=>{setMessages([STARTER]);setInput('');setMenuOpen(false)};
 const sendMessage=async(text=input)=>{const trimmed=text.trim();if(!trimmed||loading)return;const user={role:'user',text:trimmed},next=[...messages,user];setMessages(next);setInput('');setLoading(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed.');setMessages(c=>[...c,d.message]);}catch(e){setMessages(c=>[...c,{role:'model',error:true,text:e.message||'Something went wrong. Please try again.'}]);}finally{setLoading(false);ta.current?.focus()}};
 const key=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}};
 const copy=async t=>{try{await navigator.clipboard.writeText(t)}catch{}};
 return <div className="app"><header className="topbar"><div className="brand"><div className="logo"><Sparkles size={18}/></div><div><strong>Gemini Chat</strong><span>React + Vercel</span></div></div><div className="top-actions"><button className="new-chat" onClick={newChat}><MessageSquarePlus size={17}/><span>New chat</span></button><div className="menu-wrap"><button className="icon-button" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={19}/>:<Menu size={19}/>}</button>{menuOpen&&<div className="dropdown"><button onClick={()=>{setMessages([STARTER]);setMenuOpen(false)}}><Trash2 size={15}/>Clear conversation</button></div>}</div></div></header>
 <main className="chat-shell"><section className="chat-window"><div className="messages">{messages.length===1&&<div className="welcome"><div className="welcome-icon"><Bot size={30}/></div><h1>What can I help you build?</h1><p>A clean Gemini chatbot with a private server-side API key.</p><div className="suggestions">{SUGGESTIONS.map(x=><button key={x} onClick={()=>sendMessage(x)}>{x}</button>)}</div></div>}{messages.map((m,i)=><div className={'message-row '+m.role} key={i}><div className={'avatar '+m.role}>{m.role==='user'?<User size={16}/>:<Bot size={17}/>}</div><div className="message-content"><div className={'bubble '+(m.error?'error':'')}><MessageText text={m.text}/></div>{m.role==='model'&&!m.error&&<button className="copy" onClick={()=>copy(m.text)}><Copy size={13}/>Copy</button>}</div></div>)}{loading&&<div className="message-row model"><div className="avatar model"><Bot size={17}/></div><div className="bubble typing"><span/><span/><span/></div></div>}<div ref={bottomRef}/></div><div className="composer-area"><div className="composer"><textarea ref={ta} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={key} placeholder="Message Gemini..." rows="1" disabled={loading}/><button className="send" onClick={()=>sendMessage()} disabled={!input.trim()||loading}><Send size={18}/></button></div><p className="hint">Enter to send · Shift + Enter for a new line</p></div></section></main><footer><span>Gemini API runs server-side through a Vercel Function.</span><span>Never expose your API key in client code.</span></footer></div>}
function MessageText({text}){return <div>{text.split(/(\*\*.*?\*\*|`.*?`|\n)/g).map((p,i)=>p==='\n'?<br key={i}/>:p.startsWith('**')&&p.endsWith('**')?<strong key={i}>{p.slice(2,-2)}</strong>:p.startsWith('`')&&p.endsWith('`')?<code key={i}>{p.slice(1,-1)}</code>:<React.Fragment key={i}>{p}</React.Fragment>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);
